title: Eshan Iyer

email: eshaniyer@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
 This is the website that hosts Eshan Iyer's resume and various files. 

baseurl: "" # the subpath of your site, e.g. /blog

url: https://www.eshaniyer.com/ # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: eshaniyer06

github_username:  Nazchanel

linkedin_username: eshaniyer

header_pages:
 - index.markdown
 - portfolio.markdown
 - resume.markdown
 - spotify.markdown

theme: minima

minima:
  social_links:
    linkedin: eshaniyer
    github: Nazchanel

minima:
  skin: dark
  
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 

